version: '3.8'

services:
  frontend:
    image: adchamp/frontend-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:3001
    networks:
      - chat-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    image: adchamp/backend-app
    ports:
      - "3001:3000"
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    networks:
      - chat-network
    volumes:
      - ./backend:/app
      - /app/node_modules
  
networks:
  chat-network:
    driver: bridge 
