version: '3.8'

services:
  frontend:
    image: adchamp/frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:3001
    networks:
      - chat-network

  backend:
    image: adchamp/backend-app
    ports:
      - "3001:3000"
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge 